// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjsb-XvsKankZtV66jBxzaJY5cVK1IEJ4',
    appId: '1:999496392916:web:9b49158d9ecea6512e9b41',
    messagingSenderId: '999496392916',
    projectId: 'attendance-989e6',
    authDomain: 'attendance-989e6.firebaseapp.com',
    storageBucket: 'attendance-989e6.appspot.com',
    measurementId: 'G-5R5EGYDEX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrpXKGbx74kc4JDYpK7dPEpu72mWfiykg',
    appId: '1:999496392916:android:406f3f01b67d14f72e9b41',
    messagingSenderId: '999496392916',
    projectId: 'attendance-989e6',
    storageBucket: 'attendance-989e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjhwOJxOcefX6DsYGj5ktM2TIjvegsNsc',
    appId: '1:999496392916:ios:e065970e0fcd371b2e9b41',
    messagingSenderId: '999496392916',
    projectId: 'attendance-989e6',
    storageBucket: 'attendance-989e6.appspot.com',
    iosClientId: '999496392916-ej5ctolgemak6uln1cboq0cfpbb4mvug.apps.googleusercontent.com',
    iosBundleId: 'com.bi.attendanceManagement',
  );
}
